export interface BlogPost {
    id: string;
    title: string;
    excerpt: string;
    content: string;
    image: string;
    date: string;
    author: string;
    category: string;
}

export const blogPosts: BlogPost[] = [
    {
        id: "1",
        title: "The Future of Electric Bikes",
        excerpt: "Exploring the latest trends in electric bike technology",
        content: "Full content about electric bikes...",
        image: "https://i.ibb.co/5xr028MQ/image.jpg",
        date: "May 15, 2024",
        author: "Alex Rider",
        category: "Technology",
    },
    {
        id: "2",
        title: "Mountain Biking Essentials",
        excerpt: "Everything you need to start mountain biking",
        content: "Full content about mountain biking...",
        image: "https://i.ibb.co/5xr028MQ/image.jpg",
        date: "April 28, 2024",
        author: "Sarah Johnson",
        category: "Sports",
    },
    {
        id: "3",
        title: "Urban Cycling Tips for Commuters",
        excerpt: "How to safely commute with a bike in the city",
        content: "Full content about commuting by bike...",
        image: "https://i.ibb.co/5xr028MQ/image.jpg",
        date: "March 10, 2024",
        author: "James Nolan",
        category: "Lifestyle",
    },
    {
        id: "4",
        title: "Top 5 Bike Maintenance Tips",
        excerpt: "Keep your bike in top condition with these tips",
        content: "Full content about maintenance...",
        image: "https://i.ibb.co/5xr028MQ/image.jpg",
        date: "February 20, 2024",
        author: "Lara Kent",
        category: "DIY",
    },
    {
        id: "5",
        title: "Electric vs Regular Bikes: Pros & Cons",
        excerpt: "Which one suits your lifestyle best?",
        content: "Detailed comparison of electric and regular bikes...",
        image: "https://i.ibb.co/5xr028MQ/image.jpg",
        date: "January 5, 2024",
        author: "Tom Hardy",
        category: "Technology",
    },
    {
        id: "6",
        title: "Exploring Bangladesh by Bike",
        excerpt: "Best biking trails across Bangladesh",
        content: "Guide to scenic routes and safety tips...",
        image: "https://i.ibb.co/5xr028MQ/image.jpg",
        date: "May 1, 2024",
        author: "Maya Rahman",
        category: "Travel",
    },
    {
        id: "7",
        title: "Cycling for Mental Health",
        excerpt: "How biking improves your mental wellbeing",
        content: "Full content about health benefits...",
        image: "https://i.ibb.co/5xr028MQ/image.jpg",
        date: "April 15, 2024",
        author: "Dr. Sameer Alam",
        category: "Health",
    },
    {
        id: "8",
        title: "Beginner's Guide to Road Bikes",
        excerpt: "Everything a beginner should know",
        content: "Beginner-friendly advice and product suggestions...",
        image: "https://i.ibb.co/5xr028MQ/image.jpg",
        date: "March 25, 2024",
        author: "Kelly Simmons",
        category: "Guides",
    },
    {
        id: "9",
        title: "Bike-Friendly Cities in Asia",
        excerpt: "Top cities promoting cycling infrastructure",
        content: "Detailed look at urban planning and cycling access...",
        image: "https://i.ibb.co/5xr028MQ/image.jpg",
        date: "February 10, 2024",
        author: "Wei Zhang",
        category: "Travel",
    },
    {
        id: "10",
        title: "Nutrition Tips for Cyclists",
        excerpt: "Fuel your ride with the right food",
        content: "Diet and hydration strategies for bikers...",
        image: "https://i.ibb.co/5xr028MQ/image.jpg",
        date: "January 30, 2024",
        author: "Emily Clark",
        category: "Health",
    },
    {
        id: "11",
        title: "How to Choose the Right Helmet",
        excerpt: "Safety first! Here's how to pick your helmet",
        content: "Fit, safety ratings, and buying tips...",
        image: "https://i.ibb.co/5xr028MQ/image.jpg",
        date: "January 12, 2024",
        author: "Michael Reyes",
        category: "Safety",
    },
    {
        id: "12",
        title: "Cycling Events You Shouldn’t Miss in 2024",
        excerpt: "Exciting upcoming biking events worldwide",
        content: "Full list of events with dates and registration links...",
        image: "https://i.ibb.co/5xr028MQ/image.jpg",
        date: "May 22, 2024",
        author: "Sofia Khan",
        category: "Events",
    },
    {
        id: "13",
        title: "Build Your Own Bike Workshop at Home",
        excerpt: "Essential tools and setup tips",
        content: "DIY home workshop guide for cyclists...",
        image: "https://i.ibb.co/5xr028MQ/image.jpg",
        date: "March 3, 2024",
        author: "John Carpenter",
        category: "DIY",
    },
    {
        id: "14",
        title: "Women in Cycling: Breaking Barriers",
        excerpt: "Empowering stories of female cyclists",
        content: "Stories, challenges, and opportunities for women...",
        image: "https://i.ibb.co/5xr028MQ/image.jpg",
        date: "April 5, 2024",
        author: "Rina Akter",
        category: "Inspiration",
    },
    {
        id: "15",
        title: "Sustainable Commuting with Bikes",
        excerpt: "Why biking is the eco-friendly option",
        content: "Environmental impact of cycling vs driving...",
        image: "https://i.ibb.co/5xr028MQ/image.jpg",
        date: "May 5, 2024",
        author: "Tanvir Hossain",
        category: "Environment",
    },
];
